### ISSUE TITLE
[Android] NPE in VirtualView/PropHelper

### ISSUE THREAD

**Issue by Minishlink** [software-mansion/react-native-svg#1900]
# Bug

#### Unexpected behavior

Hello, on 12.4.4, there is no crash reported in our crash monitoring tool.
On 13.4.0, these crashes appear:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int com.facebook.react.bridge.ReadableArray.size()' on a null object reference
       at com.horcrux.svg.PropHelper.toMatrixData(PropHelper.java:32)
       at com.horcrux.svg.VirtualView.setMatrix(VirtualView.java:308)
       at com.horcrux.svg.VirtualViewManager.setMatrix(RenderableViewManager.java:488)
       at com.horcrux.svg.RenderableViewManager$RectViewManager.setMatrix(RenderableViewManager.java:1276)
       at com.facebook.react.viewmanagers.RNSVGRectManagerDelegate.setProperty(RNSVGRectManagerDelegate.java:33)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:46)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:84)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:142)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:93)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:792)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

This is not reproducible on our side.
Luckily we use staged rollouts so we stopped the production deployment before it reaches too many users. But that also means we have little data. This crash appeared on Android 9, 10, 12. The crash appears on multiple screens of our app so it isn't tied to a specific svg.

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 234.29 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/Library/Caches/fnm_multishells/7735_1666782573880/bin/node
    Yarn: 1.22.18 - ~/Library/Caches/fnm_multishells/7735_1666782573880/bin/yarn
    npm: 8.5.5 - ~/Library/Caches/fnm_multishells/7735_1666782573880/bin/npm
    Watchman: 2022.10.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/-/.rvm/gems/ruby-2.7.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-31 | Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 13.4.0
Old arch
Hermes enabled

**Comment by WoLewicki** [comment]
Based on types from the library, `matrix` prop should never end up being `null` (see: https://github.com/software-mansion/react-native-svg/blob/8cf406888034c6a468e652558fea8236a01a75c9/src/lib/extract/extractProps.ts#L85), which happened in your case. It was probably passed in `setNativeProps` by `Animated` or `Reanimated` somehow. Do you happen to have code in the project which changes `matrix` prop with `Animated` or `Reanimated`? If so, you should probably fix it in your codebase. I could create a PR with handling all of the `null` values for the props, but it seems rather like a problem with the codebase than library's bug.

**Comment by Minishlink** [comment]
Unfortunately, the only occurences of `matrix` in our code are in jest snapshots, we don't interact with this prop in our codebase.
And wouldn't that be catched by TypeScript anyway?

**Comment by WoLewicki** [comment]
Yeah, I think it should be caught by TS. I cannot think of other options how `matrix` could be passed to the native side with `null` value. Could you add some logs in the `Rect.tsx` file (https://github.com/software-mansion/react-native-svg/blob/8cf406888034c6a468e652558fea8236a01a75c9/src/elements/Rect.tsx#L31) and check if you don't pass `matrix` directly there? Same in `Shape.tsx` component's `setNativeProps` method (https://github.com/software-mansion/react-native-svg/blob/8cf406888034c6a468e652558fea8236a01a75c9/src/elements/Shape.tsx#L250). Maybe some other lib is doing so and it would be good to know it in order to fix it.

**Comment by Minishlink** [comment]
I didn't detect any extracted matrix prop on `Rect` or `Shape`, but on `Text` I did, does it interact with `Rect` somehow?

**Comment by wicharek** [comment]
Experiencing a similar issue. In my case it is definitely caused by `react-native-progress` package (`Circle` component, when `progress` property is set to certain values). As far as I can it doesn't set matrix prop directly though. Do not have time to investigate deeper at the moment. For now, will simply patch this package like this (solves the issue for me):

```java
public void setMatrix(ReadableArray matrixArray) {
    if (matrixArray == null) {
      return;
    }
```

**Comment by WoLewicki** [comment]
@Minishlink @wicharek can you check if https://github.com/software-mansion/react-native-svg/pull/1904 fixes your issue?

**Comment by harrisrobin** [comment]
Experiencing this as well using the v13.8.0 with react-native 0.72.3.

**Comment by TomasSestak** [comment]
Also getting this on v13.4.0 with react-native 0.70.8

**Comment by WoLewicki** [comment]
Please provide a minimal repository/snack with a reproduction so we can work on it.

**Comment by davkub** [comment]
Updating to version `13.5.0` solved our error caused by `react-native-progress`, thank you @WoLewicki
