### ISSUE TITLE
Issue with upgrading the library

### ISSUE THREAD

**Issue by pavermakov** [software-mansion/react-native-svg#1949]
I have recently upgraded react-native from 0.64.4 to 0.66.0. When tried to run the app, it failed on both platforms with the following message:

`[Error: TransformError node_modules/react-native-svg/src/elements/Shape.tsx: /node_modules/react-native-svg/src/elements/Shape.tsx: child.isClassAccessorProperty is not a function]`

Has anyone experiences a similar problem?

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 28.58 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 2021.09.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-32 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 12.4.4

**Comment by pavermakov** [comment]
Turned out the issue had nothing to do with the library. I have downgraded the following libraries and the app now works fine:

```
"@babel/core" from "7.14.6" to "7.12.9"
"@babel/runtime" from "7.14.6" to "7.12.5"
```

**Comment by ankitjpk** [comment]
@pavermakov 
I had this same issue but this fix not working.
Any other work arounds!

**Comment by divyesh-puri** [comment]
@ankitjpk You able to solve this issue?

**Comment by kabeza** [comment]
Hi
Having same issue when trying to build release apk (running app on emulator works fine)
I have executed:

`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/`

and got this error

```
error node_modules/react-native-svg/src/elements/Shape.tsx: /home/myuser/reactnative/myappname/node_modules/react-native-svg/src/elements/Shape.tsx: child.isClassAccessorProperty is not a function.
TypeError: /home/myuser/reactnative/myappname/node_modules/react-native-svg/src/elements/Shape.tsx: child.isClassAccessorProperty is not a function
    at /home/myuser/reactnative/myappname/node_modules/@babel/plugin-transform-typescript/lib/index.js:347:89
    at Array.forEach (<anonymous>)
    at PluginPass.Class (/home/myuser/reactnative/myappname/node_modules/@babel/plugin-transform-typescript/lib/index.js:340:31)
    at newFn (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitQueue (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/context.js:109:21)
```

I have in my package.json:

`
"react-native-svg": "^12.5.1",
`

devDependencies section (downgrading babel versions didn't work, keep getting same error)

 ```
"@babel/core": "^7.20.0",
 "@babel/preset-env": "^7.20.0",
 "@babel/runtime": "^7.20.0",
```

React Native info

```
System:
    OS: Linux 5.4 elementary OS 5.1.7 Hera
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 3.74 GB / 15.50 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.1.0
      System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: AI-203.7717.56.2031.7784292
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.2 => 0.71.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by ivanhoe-dev** [comment]
I had the same error, downgrade/upgrade react-native-svg didn't help me, but I finally resolved the problem by re-link  the package
`react-native unlink react-native-svg
react-native link react-native-svg`

**Comment by kabeza** [comment]
Hi @ivanhoe-dev 
I've tried running those commands, without any luck

```
warn Package react-native-screens has been ignored because it contains invalid configuration. Reason: "dependency.platforms.android.componentDescriptors" is not allowed
warn Calling react-native unlink [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```
