### ISSUE TITLE
com.facebook.react.bridge.NoSuchKeyException: payload

### ISSUE THREAD

**Issue by andreirat** [software-mansion/react-native-svg#1988]
After a release, we've seen that some Android devices crash with the error: 

Android OS versions affected: 

`Android 13`
`Android 12`
`Android 11`

```bash
com.facebook.react.bridge.NoSuchKeyException: payload
	at com.facebook.react.bridge.ReadableNativeMap.getType(ReadableNativeMap.java:180)
	at com.horcrux.svg.RenderableView.setFill(RenderableView.java:162)
	at com.horcrux.svg.RenderableViewManager.setFill(RenderableViewManager.java:2019)
	at com.horcrux.svg.RenderableViewManager$PathViewManager.setFill(RenderableViewManager.java:745)
	at com.facebook.react.viewmanagers.RNSVGPathManagerDelegate.setProperty(RNSVGPathManagerDelegate.java:63)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:46)
	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:46)
	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:144)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:77)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Versions used:
`"react-native-svg": "^13.8.0"`
`"react-native-gifted-charts": "^1.2.42"`

Does anyone experience the same issue?

**Comment by bananana0118** [comment]
how did you solve it ?? It is similar to my case

**Comment by 0b3r** [comment]
+1

**Comment by bohdanprog** [comment]
Hello @andreirat,
Can you share a simple example to reproduce that problem?
Thank you
