### ISSUE TITLE
A component created with SvgUri fails in the storybook.

### ISSUE THREAD

**Issue by uhgenie7** [software-mansion/react-native-svg#2050]
# Bug

I'm using storybook (Export React Native Storybook Components as Static Storybook Web App), tried to make a component using `import {SvgUri} from 'react-native-svg';` and check it with Storybook. 
However, an import error occurs in Storybook.

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
  at createFiberFromElement (/vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_reg-96ecf4.iframe.bundle.js:64749:15))
  at reconcileSingleElement (/vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_reg-96ecf4.iframe.bundle.js:52039:23))
  at reconcileChildFibers (/vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_reg-96ecf4.iframe.bundle.js:52097:35))
  at reconcileChildren (/vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_reg-96ecf4.iframe.bundle.js:55451:28))
  at mountIndeterminateComponent (/vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_reg-96ecf4.iframe.bundle.js:56441:5))
  at beginWork (/vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_reg-96ecf4.iframe.bundle.js:57871:16))
  at beginWork$1 (/vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_reg-96ecf4.iframe.bundle.js:63710:14))
  at performUnitOfWork (/vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_reg-96ecf4.iframe.bundle.js:62841:12))
  at workLoopSync (/vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_reg-96ecf4.iframe.bundle.js:62750:5))
```

Replacing '`import **{SvgUri}** from 'react-native-svg';`' with '`import **SvgUri** from 'react-native-svg';`' makes this error go away, but this is not what I want. 

The strange thing is, Components using "import Svg, {Path} from 'react-native-svg';", not fail. 
Only {SvgUri} is fail.

## Environment info

React native info output:

```bash
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 190.96 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.10.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version:
```
    "react-native-svg": "12.4.3",
    "react-native-svg-transformer": "1.0.0",
    "storybook/react": 7.0
    "storybook/react-native": 6.5
    "react-native-web": "0.18.9"

```

**Comment by bohdanprog** [comment]
Hello @uhgenie7,
Can you share a simple example of how we can reproduce that?
thank you :)
