### ISSUE TITLE
on EAS build command "eas build -p android --profile preview" i am getting this failure every time. Able to run locally without any error.

### ISSUE THREAD

**Issue by jareesh** [software-mansion/react-native-svg#2146]
on EAS build command "eas build -p android --profile preview" i am getting this failure every time. Able to run locally without any error.

Any help is appreciated 

# EAS Build error
> Task :expo-splash-screen:createFullJarRelease
> Task :app:createBundleReleaseJsAndAssets
[stderr] Error: Unable to resolve module react-native-svg from /home/expo/workingdir/build/sale-ex-app/node_modules/native-base/src/components/primitives/Icon/nbSvg.tsx: react-native-svg could not be found within the project or in these directories:

[stderr]  node_modules/native-base/node_modules
[stderr]  node_modules
[stderr] > 1 | export { Svg, G, Path, Polygon, Line, Circle, Rect } from 'react-native-svg';
[stderr]       |                                                            ^
[stderr]   2  |
[stderr] Error: Unable to resolve module react-native-svg from /home/expo/workingdir/build/sale-ex-app/node_modules/native-base/src/components/primitives/Icon/nbSvg.tsx: react-native-svg could not be found within the project or in these directories:
[stderr]   node_modules/native-base/node_modules
[stderr]   node_modules
[stderr] > 1 | export { Svg, G, Path, Polygon, Line, Circle, Rect } from 'react-native-svg';
[stderr]     |                                                            ^
[stderr]   2 |
[stderr]     at ModuleResolver.resolveDependency (/home/expo/workingdir/build/sale-ex-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
[stderr]     at DependencyGraph.resolveDependency (/home/expo/workingdir/build/sale-ex-app/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
[stderr]     at Object.resolve (/home/expo/workingdir/build/sale-ex-app/node_modules/metro/src/lib/transformHelpers.js:169:21)
[stderr]     at Graph._resolveDependencies (/home/expo/workingdir/build/sale-ex-app/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
[stderr]     at Graph._processModule (/home/expo/workingdir/build/sale-ex-app/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
[stderr]     at runMicrotasks (<anonymous>)
[stderr]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[stderr]     at async Graph._addDependency (/home/expo/workingdir/build/sale-ex-app/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
[stderr]     at async Promise.all (index 3)
[stderr]     at async Graph._processModule (/home/expo/workingdir/build/sale-ex-app/node_modules/metro/src/DeltaBundler/Graph.js:

**Comment by jareesh** [comment]
It looks like i mixed up in adding components using yarn and npm and that created the issue.
I removed node modules and did yarn install and
did " yarn add react-native-svg" which in turn added the dependencies properly into the package.json.
Build successful, now
