### ISSUE TITLE
Fatal Exception: java.lang.Error Invalid number formating character 'N'

### ISSUE THREAD

**Issue by Bob-MYMC** [software-mansion/react-native-svg#2245]
APP crashes on some Android devices with following stack track when session starts. The crash cannot be reproduced on Emulator or other devices.

The SVG component was used in previous version with `react-native-svg: "12.5.0"`, and no crash issue
Although the SVG component has been removed from in current version on the loading screen, the app gets the crash issue.

---
Current APP info:
- react-native: 0.71.7
- react: 18.2.0
- react-native-svg: 13.14.0

---
```
Fatal Exception: java.lang.Error: Invalid number formating character 'N' (i=1, s=MNaN NaN
          A45 45 0 0 1 48 3)
       at com.horcrux.svg.PathParser.parse_number(PathParser.java:627)
       at com.horcrux.svg.PathParser.parse_list_number(PathParser.java:594)
       at com.horcrux.svg.PathParser.parse(PathParser.java:108)
       at com.horcrux.svg.PathView.setD(PathView.java:28)
       at com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:751)
       at com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:740)
       at com.facebook.react.viewmanagers.RNSVGPathManagerDelegate.setProperty(RNSVGPathManagerDelegate.java:112)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:46)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:84)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:188)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:909)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1397)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
       at android.view.Choreographer.doFrame(Choreographer.java:934)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by kieyanmamicheOtO** [comment]
Hey, did you figure out this issue? I am getting the same error and am stuck on it as well. Thanks!

**Comment by Bob-MYMC** [comment]
the error seems from the lib react-native-progress

**Comment by ryelibra37** [comment]
@Bob-MYMC, I'm getting the same error in my app on firebase, and users reporting crashes which I think are related. But I cannot replicate on any emulators or physical devices I have. How did you figure out it was coming from the lib react-native-progress? I don't have this package, but I have other packages that are dependant on rnsvg.

My error message reads like so:

java.lang.Error - Invalid number formating character 'N'

Fatal Exception: java.lang.Error
Unexpected end (s=M )
com.horcrux.svg.PathParser.parse_number (PathParser.java:606)
com.horcrux.svg.PathParser.parse_list_number (PathParser.java:594)
com.horcrux.svg.PathParser.parse (PathParser.java:108)
com.horcrux.svg.PathView.setD (PathView.java:28)
com.horcrux.svg.RenderableViewManager$PathViewManager.setD (RenderableViewManager.java:751)
com.horcrux.svg.RenderableViewManager$PathViewManager.setD (RenderableViewManager.java:740)
com.facebook.react.viewmanagers.RNSVGPathManagerDelegate.setProperty (RNSVGPathManagerDelegate.java:112)
com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:46)
com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:84)
com.facebook.react.uimanager.ViewManager.createViewInstance (ViewManager.java:188)
com.facebook.react.uimanager.ViewManager.createView (ViewManager.java:115)
com.facebook.react.uimanager.NativeViewHierarchyManager.createView (NativeViewHierarchyManager.java:281)
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java:194)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations (UIViewOperationQueue.java:1110)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1081)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1142)

**Comment by ryelibra37** [comment]
@bohdanprog unfortunately not, because I have no way of replicating the error on a device or simulator, so I could make a bare copy of my repo but I would not know whether it was causing this error. It mainly seems to be affecting google pixel 7 pro devices.

**Comment by Bob-MYMC** [comment]
> @Bob-MYMC, I'm getting the same error in my app on firebase, and users reporting crashes which I think are related. But I cannot replicate on any emulators or physical devices I have. How did you figure out it was coming from the lib react-native-progress? I don't have this package, but I have other packages that are dependant on rnsvg.
> 
> 
> 
> My error message reads like so:
> 
> 
> 
> java.lang.Error - Invalid number formating character 'N'
> 
> 
> 
> Fatal Exception: java.lang.Error
> 
> Unexpected end (s=M )
> 
> com.horcrux.svg.PathParser.parse_number (PathParser.java:606)
> 
> com.horcrux.svg.PathParser.parse_list_number (PathParser.java:594)
> 
> com.horcrux.svg.PathParser.parse (PathParser.java:108)
> 
> com.horcrux.svg.PathView.setD (PathView.java:28)
> 
> com.horcrux.svg.RenderableViewManager$PathViewManager.setD (RenderableViewManager.java:751)
> 
> com.horcrux.svg.RenderableViewManager$PathViewManager.setD (RenderableViewManager.java:740)
> 
> com.facebook.react.viewmanagers.RNSVGPathManagerDelegate.setProperty (RNSVGPathManagerDelegate.java:112)
> 
> com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:46)
> 
> com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:84)
> 
> com.facebook.react.uimanager.ViewManager.createViewInstance (ViewManager.java:188)
> 
> com.facebook.react.uimanager.ViewManager.createView (ViewManager.java:115)
> 
> com.facebook.react.uimanager.NativeViewHierarchyManager.createView (NativeViewHierarchyManager.java:281)
> 
> com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java:194)
> 
> com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations (UIViewOperationQueue.java:1110)
> 
> com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1081)
> 
> com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
> 
> com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
> 
> com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
> 
> android.view.Choreographer$CallbackRecord.run (Choreographer.java:1142)

the crash has not been reported again since the lib was replaced

**Comment by bohdanprog** [comment]
> @bohdanprog unfortunately not, because I have no way of replicating the error on a device or simulator, so I could make a bare copy of my repo but I would not know whether it was causing this error. It mainly seems to be affecting google pixel 7 pro devices.

Okay, if you find a way to reproduce that issue, you can open a new issue, with a simple repro of that problem.
Thank you

**Comment by fullychargedup** [comment]
Im having this issue too. Does anyone know how to fix it. Im on         "react-native-svg": "13.4.0",

**Comment by bohdanprog** [comment]
@fullychargedup Can you share any example of how to reproduce that issue, please?

**Comment by Nader-CS** [comment]
same issue
```
     Fatal Exception: java.lang.IllegalArgumentException: Invalid number formating character 'N' (i=46, s=M 0 -129.758242 A 129.758242 129.758242 0 0 1 NaN NaN L NaN NaN A 0 0 0 0 0 0 0 Z )
       at com.horcrux.svg.PathParser.parse_number(PathParser.java:631)
       at com.horcrux.svg.PathParser.parse_list_number(PathParser.java:598)
       at com.horcrux.svg.PathParser.parse(PathParser.java:220)
       at com.horcrux.svg.PathView.setD(PathView.java:28)
       at com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:756)
       at com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:745)
       at com.facebook.react.viewmanagers.RNSVGPathManagerDelegate.setProperty(RNSVGPathManagerDelegate.java:106)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:46)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:77)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:181)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:108)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1121)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1092)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:2185)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:2196)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1365)
       at android.view.Choreographer.doFrame(Choreographer.java:1207)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:2114)
       at android.os.Handler.handleCallback(Handler.java:996)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:302)
       at android.app.ActivityThread.main(ActivityThread.java:9652)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
```

**Comment by bohdanprog** [comment]
@Nader-CS  any example related to that issue?

**Comment by fullychargedup** [comment]
Hi i dont have an example i can share as our code is private, but I can say we use Instabug and this only happens on the galaxy S22, S23 and S24 phones. I dont have one of these physical devices so can't reproduce but the logs show those are the issue phones.

**Comment by Nader-CS** [comment]
```
import React, {useMemo} from 'react';
import {
  Dimensions,
  Image,
  Platform,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import {useTranslation} from 'react-i18next';
import {PieChart} from 'react-native-chart-kit';
import {useGetPointsAnalyticsQuery} from '@services';
import {colors, typo} from '@common';
import {convertEnglishNumbersToArabic} from '@utils/helpers';
import {moderateVerticalScale, moderateScale} from 'react-native-size-matters';
import {second_logo} from '@assets';
import {commonStyles} from '@utils/constants';
import {useSelector} from 'react-redux';
import {getUserCountry} from '@selectors';

const width = Dimensions.get('screen').width;

const chartConfig = {
  color: (opacity = 1) => colors.colorWithAlpha(colors.black, opacity),
};

const PointsChart = ({type}) => {
  const {t} = useTranslation();
  const userCountry = useSelector(getUserCountry);
  const {data} = useGetPointsAnalyticsQuery();

  const currentPointPercentage = useMemo(
    () =>
      data?.points_analytics?.points && data?.points_analytics?.total_earned > 0
        ? (data?.points_analytics?.points * 100) /
          data?.points_analytics?.total_earned
        : 0,
    [data],
  );

  const totalRedeemedPercentage = useMemo(
    () =>
      data?.points_analytics?.total_redeemed &&
      data?.points_analytics?.total_earned > 0
        ? (data?.points_analytics?.total_redeemed * 100) /
          data?.points_analytics?.total_earned
        : 0,
    [data],
  );

  const totalExpiredPercentage = useMemo(
    () =>
      data?.points_analytics?.expired &&
      data?.points_analytics?.total_earned > 0
        ? (data?.points_analytics?.expired * 100) /
          data?.points_analytics?.total_earned
        : 0,
    [data],
  );

  const chartData = useMemo(
    () => [
      {
        points: currentPointPercentage,
        color: colors.brown,
      },
      {
        points: totalRedeemedPercentage,
        color: colors.sand_dune,
      },
      {
        points: totalExpiredPercentage,
        color: colors.main_red,
      },
    ],
    [currentPointPercentage, totalRedeemedPercentage, totalExpiredPercentage],
  );

  const totalPoints = data?.points_analytics?.points || 0;

  return (
    <View style={styles.chartContainer}>
      <PieChart
        data={chartData}
        width={width}
        height={moderateScale(320, 0.25)}
        paddingLeft={width / 4}
        chartConfig={chartConfig}
        accessor="points"
        backgroundColor="transparent"
        hasLegend={false}
      />
      <View style={styles.insideChart}>
        <Image style={styles.logo} source={second_logo} />
        <Text style={styles.points} allowFontScaling={false}>
          {convertEnglishNumbersToArabic(totalPoints)}
        </Text>
        <Text style={styles.pointsBalance} allowFontScaling={false}>
          {t('points_balance')}
        </Text>
        <Text style={styles.equalsTo} allowFontScaling={false}>
          {t('equals_to')}{' '}
          <Text style={styles.equalsToPrice} allowFontScaling={false}>
            {convertEnglishNumbersToArabic(
              Number(totalPoints / userCountry?.redeeming_rate || 0).toFixed(2),
            )}
          </Text>{' '}
          {userCountry?.country?.currency}
        </Text>
      </View>
    </View>
  );
};

export default PointsChart;

const styles = StyleSheet.create({
  chartContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  insideChart: {
    height: moderateVerticalScale(200, 0.25),
    width: moderateScale(200, 0.25),
    backgroundColor: colors.white,
    zIndex: 10,
    borderRadius: moderateScale(200),
    position: 'absolute',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Platform.OS == 'ios' ? commonStyles.gap / 1.5 : 0,
  },
  logo: {
    width: moderateScale(125),
    height: moderateVerticalScale(27),
    resizeMode: 'contain',
  },
  points: {
    fontSize: commonStyles.biggerFontSize,
    fontFamily: typo.sofiaBroBlack,
    color: colors.brown,
  },
  pointsBalance: {
    fontSize: commonStyles.thirdFontSize,
    fontFamily: typo.sofiaBroRegular,
    color: colors.black,
  },
  equalsTo: {
    fontSize: commonStyles.secondaryFontSize,
    color: colors.black,
    paddingBottom: moderateVerticalScale(15),
    fontFamily: typo.sofiaBroRegular,
  },
  equalsToPrice: {
    fontFamily: typo.sofiaBroBlack,
    color: colors.brown,
  },
});

```

**Comment by fullychargedup** [comment]
any help on this?

**Comment by fullychargedup** [comment]
i updated to v14 and still getting the issue.

Your app just crashed. See the error below.
java.lang.Error: Invalid number formating character 'N' (i=58, s=M 101.57572230590169, 253.8288770053476 
A 2.5 2.5 0 0 0, NaN, 253.8288770053476 
L NaN, 253.8288770053476 
A 2.5 2.5 0 0 0, NaN, 253.8288770053476 
L NaN, 253.8288770053476 
A 2.5 2.5 0 0 0, NaN, 253.8288770053476 
L NaN, 253.8288770053476 
A 2.5 2.5 0 0 0, 101.57572230590169, 253.8288770053476 
 z)
  com.horcrux.svg.PathParser.parse_number(PathParser.java:627)
  com.horcrux.svg.PathParser.parse_list_number(PathParser.java:594)
  com.horcrux.svg.PathParser.parse(PathParser.java:217)
  com.horcrux.svg.PathView.setD(PathView.java:28)
  com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:751)
  com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:740)
  com.facebook.react.viewmanagers.RNSVGPathManagerDelegate.setProperty(RNSVGPathManagerDelegate.java:112)
  com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:46)
  com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:84)
  com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:188)
  com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
  com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
  com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
  com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
  com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
  com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
  com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
  com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
  android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)
  android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
  android.view.Choreographer.doCallbacks(Choreographer.java:952)
  android.view.Choreographer.doFrame(Choreographer.java:878)
  android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
  android.os.Handler.handleCallback(Handler.java:958)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loopOnce(Looper.java:205)
  android.os.Looper.loop(Looper.java:294)
  android.app.ActivityThread.main(ActivityThread.java:8177)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)

**Comment by fullychargedup** [comment]
Bob-MYMCL: "the error seems from the lib react-native-progress"

@Bob-MYMC How do you know this? and at what version what this lib taken out of this library (or was it)?

**Comment by Hammad-Khurshid** [comment]
> Bob-MYMCL: "the error seems from the lib react-native-progress"
> 
> @Bob-MYMC How do you know this? and at what version what this lib taken out of this library (or was it)?


@fullychargedup 
This issue is caused by NaN values. Please ensure that none of your functions are returning or containing NaN values.

**Comment by jsimonassi** [comment]
@bohdanprog 

#### I found a dataset that allows me to reproduce the issue.

In my application, I use Victory Chart to render charts. The issue specifically occurs with VictoryBar when y and y0 have the same values.

I can't share the entire implementation as it is proprietary code, but here is a snippet that can be used to reproduce the issue:

```tsx

const mockedData = [
  {
      "label": "",
      "x": 10,
      "y": 30,
      "y0": 30
  }
]

//Tsx
        <VictoryBar
         //other props...
          data={mockedData}
          labelComponent={
            <VictoryTooltip
              renderInPortal={false}
              flyoutComponent={
                <ChartTooltip chartDataItems={filteredSleepWeeklyHistory} />
              }
            />
          }
        />

```

In this case, if y0 has a different value (29 or 31, for example), I don't get any crash. When the value of y and y0 are the same, the application crashes with this log:

```log
java.lang.Error: Invalid number formating character 'N' (i=88, s=M 118.9010923591998, 124.61537775908738 
                                                                                                    A 2.3076921807238406 2.3076921807238406 0 0 0, NaN, 124.61537775908738 
                                                                                                    L NaN, 124.61537775908738 
                                                                                                    A 2.3076921807238406 2.3076921807238406 0 0 0, NaN, 124.61537775908738 
                                                                                                    L NaN, 124.61537775908738 
                                                                                                    A 2.3076921807238406 2.3076921807238406 0 0 0, NaN, 124.61537775908738 
                                                                                                    L NaN, 124.61537775908738 
                                                                                                    A 2.3076921807238406 2.3076921807238406 0 0 0, 122.74724599373951, 124.61537775908738 
                                                                                                     z)
                                                                                                    	at com.horcrux.svg.PathParser.parse_number(PathParser.java:627)
                                                                                                    	at com.horcrux.svg.PathParser.parse_list_number(PathParser.java:594)
                                                                                                    	at com.horcrux.svg.PathParser.parse(PathParser.java:217)
                                                                                                    	at com.horcrux.svg.PathView.setD(PathView.java:28)
                                                                                                    	at com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:756)
                                                                                                    	at com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:745)
                                                                                                    	at com.facebook.react.viewmanagers.RNSVGPathManagerDelegate.setProperty(RNSVGPathManagerDelegate.java:108)
                                                                                                    	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:46)
                                                                                                    	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:77)
                                                                                                    	at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:142)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:93)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:926)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1037)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue.-$$Nest$mflushPendingBatches(Unknown Source:0)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1097)
                                                                                                    	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
                                                                                                    	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
                                                                                                    	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1688)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1154)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1070)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9063)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```


#### Here is some information from my environment:
- Package versions:
    "react-native-svg": "13.8.0",
    "victory-native": "36.8.3",
    "react-native": "0.73.0"

- Tested device:

    1. Galaxy S22 - Android 14.

     According to firebase logs, the issue also occurs on:

     2.Redmi 9 - Android 12
     3.Galaxy S20 FE - Android 13

My application uses a lot of graphics and I am interested in solving this issue. I am going to add a fix to my application as a workaround for now. If you need any more information, I can provide it.

I am currently investigating the library to try to solve the issue. If I can, I will open a PR for it. Please let me know if any updates are made on this issue.
